name: CI

on:
  - push
  - pull_request

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install up-to-date packaging toolchain.
      - run: python3 -m pip install --upgrade pip setuptools wheel
      - run: python3 -m pip install --upgrade build

      # Build dists.
      - run: python3 -m build

      # Upload dists as workflow artifacts.
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  test-dist:
    needs: build-dist
    name: test-dist (python=${{ matrix.python }} os=${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          mamba-version: "*"
          channels: conda-forge,bioconda
          channel-priority: true
          activate-environment: test
      - run: cat ~/.profile || true
      - run: cat ~/.bashrc || true

      - name: Set up test environment
        run: |
          mamba install augur auspice snakemake
          # The small build we'll use as an integration test case.
          git clone https://github.com/nextstrain/zika-tutorial

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Install Nextstrain CLI
        run: python3 -m pip install --upgrade --find-links dist/ 'nextstrain-cli[dev]'

      - run: conda info
      - run: conda list

      - name: Check python version
        run: |
          # Assert that we're on the expected Python version, in case the GH
          # Actions environment is messed up.
          python3 --version | grep -F 'Python ${{ matrix.python }}.'

      - name: Run Nextstrain CLI commands
        run: |
          nextstrain version --verbose
          nextstrain check-setup --set-default

          # XXX TODO: Stop ignoring errors once `update` is improved.  See
          # <https://github.com/nextstrain/cli/issues/87>.
          nextstrain update || true

          nextstrain version --verbose

      - name: Run pytest
        run: pytest -v

      - if: runner.os != 'macOS'
        name: Build zika-tutorial with --docker
        run: |
          git -C zika-tutorial clean -dfqx
          nextstrain build --docker --cpus 2 zika-tutorial

      - name: Build zika-tutorial with --native
        run: |
          git -C zika-tutorial clean -dfqx
          nextstrain build --native --cpus 2 zika-tutorial

  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Upgrade Python toolchain
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Setup docs build environment
        run: python3 -m pip install --upgrade -e '.[dev]'

      - name: Make docs with warnings fatalized
        run: make -C doc dirhtml
        env:
          SPHINXOPTS: -W --keep-going
