name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: python=${{ matrix.python }} os=${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          mamba-version: "*"
          channels: conda-forge,bioconda
          channel-priority: true
          activate-environment: test

      - name: Set up test environment
        run: |
          mamba install augur snakemake
          git clone https://github.com/nextstrain/zika-tutorial

      - name: Install Nextstrain CLI
        run: pip install --upgrade -e '.[dev]'

      - run: conda info
      - run: conda list

      - name: Run Nextstrain CLI commands
        run: |
          nextstrain version --verbose
          nextstrain check-setup --set-default

          # XXX TODO: Stop ignoring errors once `update` is improved.  See
          # <https://github.com/nextstrain/cli/issues/87>.
          nextstrain update || true

          nextstrain version --verbose

      - name: Run pytest
        run: pytest -v

      - if: runner.os != 'macOS'
        name: Build zika-tutorial with --docker
        run: |
          git -C zika-tutorial clean -dfqx
          nextstrain build --docker --cpus 2 zika-tutorial

      - name: Build zika-tutorial with --native
        run: |
          git -C zika-tutorial clean -dfqx
          nextstrain build --native --cpus 2 zika-tutorial

  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Upgrade Python toolchain
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Setup docs build environment
        run: python3 -m pip install --upgrade -e '.[dev]'

      - name: Make docs with warnings fatalized
        run: make -C doc dirhtml
        env:
          SPHINXOPTS: -W --keep-going
